# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ('pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Date of birth')),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
                'ordering': ('join_date',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='pub_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Person'),
        ),
    ]
