# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_placeholder',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_placeholder',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='OAuth id'),
        ),
    ]
