# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='Join date'),
        ),
    ]
