# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_unsubscribe',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date unsubscribe'),
        ),
    ]
