# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-01-09 14:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(choices=[('0', 'NULL'), ('1', 'CAPITOLE'), ('2', 'SAINT-GEORGES'), ('3', 'JUNCASSE - ARGOULETS'), ('4', 'GRAMONT'), ('5', 'LA TERRASSE'), ('6', "ZONES D'ACTIVITES SUD"), ('7', 'FONTAINE-LESTANG'), ('8', 'PONT-DES-DEMOISELLES'), ('9', "PATTE D'OIE"), ('10', 'LE BUSCA'), ('11', 'CROIX-DE-PIERRE'), ('12', 'REYNERIE'), ('13', 'MATABIAU'), ('14', 'FAOURETTE'), ('15', 'SAINT-ETIENNE'), ('16', 'SAINT-SIMON'), ('17', 'LES IZARDS'), ('18', 'SAINT-MARTIN-DU-TOUCH'), ('19', 'LES CHALETS'), ('20', 'LARDENNE'), ('21', 'ARENES'), ('22', 'AMIDONNIERS'), ('23', 'MIRAIL-UNIVERSITE'), ('24', 'LES PRADETTES'), ('25', 'COMPANS'), ('26', 'GINESTOUS'), ('27', 'SAINT-MICHEL'), ('28', 'FER-A-CHEVAL'), ('29', 'BELLEFONTAINE'), ('30', 'SOUPETARD'), ('31', 'PAPUS'), ('32', 'POUVOURVILLE'), ('33', 'BASSO-CAMBO'), ('34', 'ARNAUD BERNARD'), ('35', 'SAINT-AUBIN - DUPUY'), ('36', 'JULES JULIEN'), ('37', 'CROIX-DAURADE'), ('38', 'CASSELARDIT'), ('39', 'MINIMES'), ('40', 'RAMIER'), ('41', 'LA CEPIERE'), ('42', 'EMPALOT'), ('43', 'LALANDE'), ('44', 'RANGUEIL - CHR - FACULTES'), ('45', 'CARMES'), ('46', 'LA FOURGUETTE'), ('47', 'BARRIERE-DE-PARIS'), ('48', 'MONTAUDRAN - LESPINET'), ('49', 'SAINT-AGNE'), ('50', 'PURPAN'), ('51', 'SAUZELONG - RANGUEIL'), ('52', 'SAINT-CYPRIEN'), ('53', 'BAGATELLE'), ('54', 'GUILHEMERY'), ('55', 'MARENGO - JOLIMONT'), ('56', 'COTE PAVEE'), ('57', "CHATEAU-DE-L'HERS"), ('58', 'ROSERAIE'), ('59', 'BONNEFOY'), ('60', 'SEPT DENIERS')], max_length=2, verbose_name='name district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
