# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='buy_place',
            field=models.CharField(choices=[('1', 'grande distribution'), ('2', 'artisan'), ('3', 'magasin specialise'), ('4', 'indefini')], max_length=2, verbose_name='buy place'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='object_state',
            field=models.CharField(choices=[('1', 'mauvais etat'), ('2', 'etat moyen'), ('3', 'bon etat')], max_length=2, verbose_name='stateObject'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='situation',
            field=models.CharField(choices=[('1', 'a vendre'), ('2', 'a donner'), ('3', 'a debarrasser')], max_length=2, verbose_name='situation'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type_place',
            field=models.CharField(choices=[('1', 'chez un particulier'), ('2', 'dans la rue'), ('3', 'dans un point de collecte')], max_length=2, verbose_name='type place '),
        ),
        migrations.AlterField(
            model_name='advert',
            name='volume',
            field=models.CharField(choices=[('1', 'peu encombrant'), ('2', 'encombrant'), ('3', 'tres encombrant')], max_length=2, verbose_name='volume advert'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('1', 'mobilier'), ('2', 'decos'), ('3', 'jardin'), ('4', 'materiaux'), ('5', 'electromenager'), ('6', 'petits_electromenagers'), ('7', 'textiles'), ('8', 'vaisselles'), ('9', 'transports'), ('10', 'divers')], max_length=2, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='centerofinterest',
            name='name_center_of_interest',
            field=models.CharField(blank=True, choices=[('1', 'sport'), ('2', 'theatre'), ('3', 'cinema'), ('4', 'voyage'), ('5', 'musique'), ('6', 'jeux_videos'), ('7', 'informatique'), ('8', 'recyclage'), ('9', 'jardinage'), ('10', 'animaux'), ('11', 'photographie'), ('12', 'lecture'), ('13', 'peinture'), ('14', 'decoration_interieure'), ('15', 'peche'), ('16', 'camping'), ('17', 'mode'), ('18', 'chasse'), ('19', 'automobile'), ('20', 'cuisine'), ('21', 'autres')], max_length=2, null=True, verbose_name='name center of interest'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='recovery_type',
            field=models.CharField(choices=[('1', 'emballage'), ('2', 'verre'), ('3', 'textile')], max_length=2, verbose_name='recovery type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_size',
            field=models.CharField(blank=True, choices=[('1', 'petite voiture'), ('2', 'moyenne voiture'), ('3', 'grande voiture')], max_length=2, null=True, verbose_name='car size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=2, null=True),
        ),
    ]
