# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('pub_date',), 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('join_date',), 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='person',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
