# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20170107_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='home_adress',
            new_name='home_address',
        ),
    ]
