# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20170111_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Complement address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(max_length=1028, verbose_name='Street name'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_state',
            field=models.CharField(choices=[('1', 'en ligne'), ('2', 'expire'), ('3', 'recupere'), ('4', 'valide'), ('5', 'supprimer')], max_length=10, verbose_name='Advert state'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='buy_place',
            field=models.CharField(choices=[('1', 'grande distribution'), ('2', 'artisan'), ('3', 'magasin specialise'), ('4', 'indefini')], max_length=20, verbose_name='buy place'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='object_state',
            field=models.CharField(choices=[('1', 'mauvais etat'), ('2', 'etat moyen'), ('3', 'bon etat')], max_length=20, verbose_name='stateObject'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='situation',
            field=models.CharField(choices=[('1', 'a vendre'), ('2', 'a donner'), ('3', 'a debarrasser')], max_length=20, verbose_name='situation'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title Advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='type_place',
            field=models.CharField(choices=[('1', 'chez un particulier'), ('2', 'dans la rue'), ('3', 'dans un point de collecte')], max_length=20, verbose_name='type place '),
        ),
        migrations.AlterField(
            model_name='advert',
            name='volume',
            field=models.CharField(choices=[('1', 'peu encombrant'), ('2', 'encombrant'), ('3', 'tres encombrant')], max_length=20, verbose_name='volume advert'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('1', 'mobilier'), ('2', 'decos'), ('3', 'jardin'), ('4', 'materiaux'), ('5', 'electromenager'), ('6', 'petits_electromenagers'), ('7', 'textiles'), ('8', 'vaisselles'), ('9', 'transports'), ('10', 'divers')], max_length=20, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='centerofinterest',
            name='name_center_of_interest',
            field=models.CharField(blank=True, choices=[('1', 'sport'), ('2', 'theatre'), ('3', 'cinema'), ('4', 'voyage'), ('5', 'musique'), ('6', 'jeux_videos'), ('7', 'informatique'), ('8', 'recyclage'), ('9', 'jardinage'), ('10', 'animaux'), ('11', 'photographie'), ('12', 'lecture'), ('13', 'peinture'), ('14', 'decoration_interieure'), ('15', 'peche'), ('16', 'camping'), ('17', 'mode'), ('18', 'chasse'), ('19', 'automobile'), ('20', 'cuisine'), ('21', 'autres')], max_length=20, null=True, verbose_name='name center of interest'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(choices=[('0', 'NULL'), ('1', 'CAPITOLE'), ('2', 'SAINT-GEORGES'), ('3', 'JUNCASSE - ARGOULETS'), ('4', 'GRAMONT'), ('5', 'LA TERRASSE'), ('6', "ZONES D'ACTIVITES SUD"), ('7', 'FONTAINE-LESTANG'), ('8', 'PONT-DES-DEMOISELLES'), ('9', "PATTE D'OIE"), ('10', 'LE BUSCA'), ('11', 'CROIX-DE-PIERRE'), ('12', 'REYNERIE'), ('13', 'MATABIAU'), ('14', 'FAOURETTE'), ('15', 'SAINT-ETIENNE'), ('16', 'SAINT-SIMON'), ('17', 'LES IZARDS'), ('18', 'SAINT-MARTIN-DU-TOUCH'), ('19', 'LES CHALETS'), ('20', 'LARDENNE'), ('21', 'ARENES'), ('22', 'AMIDONNIERS'), ('23', 'MIRAIL-UNIVERSITE'), ('24', 'LES PRADETTES'), ('25', 'COMPANS'), ('26', 'GINESTOUS'), ('27', 'SAINT-MICHEL'), ('28', 'FER-A-CHEVAL'), ('29', 'BELLEFONTAINE'), ('30', 'SOUPETARD'), ('31', 'PAPUS'), ('32', 'POUVOURVILLE'), ('33', 'BASSO-CAMBO'), ('34', 'ARNAUD BERNARD'), ('35', 'SAINT-AUBIN - DUPUY'), ('36', 'JULES JULIEN'), ('37', 'CROIX-DAURADE'), ('38', 'CASSELARDIT'), ('39', 'MINIMES'), ('40', 'RAMIER'), ('41', 'LA CEPIERE'), ('42', 'EMPALOT'), ('43', 'LALANDE'), ('44', 'RANGUEIL - CHR - FACULTES'), ('45', 'CARMES'), ('46', 'LA FOURGUETTE'), ('47', 'BARRIERE-DE-PARIS'), ('48', 'MONTAUDRAN - LESPINET'), ('49', 'SAINT-AGNE'), ('50', 'PURPAN'), ('51', 'SAUZELONG - RANGUEIL'), ('52', 'SAINT-CYPRIEN'), ('53', 'BAGATELLE'), ('54', 'GUILHEMERY'), ('55', 'MARENGO - JOLIMONT'), ('56', 'COTE PAVEE'), ('57', "CHATEAU-DE-L'HERS"), ('58', 'ROSERAIE'), ('59', 'BONNEFOY'), ('60', 'SEPT DENIERS')], max_length=20, verbose_name='name district'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='recovery_type',
            field=models.CharField(choices=[('1', 'emballage'), ('2', 'verre'), ('3', 'textile')], max_length=20, verbose_name='recovery type'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(choices=[('1', 'armoire'), ('2', 'buffet'), ('3', 'canape'), ('4', 'chaise'), ('5', 'commode'), ('6', 'etagere'), ('7', 'fauteuil'), ('8', 'fenetre'), ('9', 'lit'), ('10', 'matelas'), ('11', 'porte'), ('12', 'pouf'), ('13', 'table'), ('14', 'table_chevet'), ('15', 'tabouret'), ('16', 'bougeoire'), ('17', 'cadre'), ('18', 'coussin'), ('19', 'luminaire'), ('20', 'miroir'), ('21', 'pendule'), ('22', 'rideaux'), ('23', 'tapis'), ('24', 'vase'), ('25', 'barbecue'), ('26', 'echelle'), ('27', 'hamac'), ('28', 'parasol'), ('29', 'bois'), ('30', 'carton'), ('31', 'ceramique'), ('32', 'metal'), ('33', 'papier'), ('34', 'plastique'), ('35', 'tissu'), ('36', 'verre'), ('37', 'aspirateur'), ('38', 'climatiseur'), ('39', 'congelateur'), ('40', 'four'), ('41', 'refrigerateur'), ('42', 'lave_vaisselle'), ('43', 'lave_linge'), ('44', 'poele_a_bois'), ('45', 'ventilateur'), ('46', 'balance'), ('47', 'batteur'), ('48', 'bouilloire'), ('49', 'cafetiere'), ('50', 'crepiere'), ('51', 'fer_a_repasser'), ('52', 'friteuse'), ('53', 'gauffrier'), ('54', 'grille_pain'), ('55', 'machine_a_fondue'), ('56', 'micro_onde'), ('57', 'mixeur'), ('58', 'pese_personne'), ('59', 'plancha'), ('60', 'plaque_de_cuisson'), ('61', 'raclette'), ('62', 'radiateur'), ('63', 'bonnet'), ('64', 'chaussure'), ('65', 'chemise'), ('66', 'couverture'), ('67', 'gant'), ('68', 'pantalon'), ('69', 'pull'), ('70', 'serviette'), ('71', 'short'), ('72', 't_shirt'), ('73', 'veste'), ('74', 'assiette'), ('75', 'carsserole'), ('76', 'couvert'), ('77', 'faitout'), ('78', 'plateau'), ('79', 'poele'), ('80', 'saladier'), ('81', 'theiere'), ('82', 'verre'), ('83', 'roller'), ('84', 'skateboard'), ('85', 'ski'), ('86', 'snowboard'), ('87', 'trottinette'), ('88', 'velo'), ('89', 'baignoire'), ('90', 'bocal'), ('91', 'boite'), ('92', 'bouteille'), ('93', 'lavabo'), ('94', 'sac'), ('95', 'tonneau'), ('96', 'valise')], max_length=20, verbose_name='Sub-category name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_size',
            field=models.CharField(blank=True, choices=[('1', 'petite voiture'), ('2', 'moyenne voiture'), ('3', 'grande voiture')], max_length=20, null=True, verbose_name='car size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=604, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=604, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='OAuth id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_professional_category',
            field=models.CharField(blank=True, choices=[('1', 'artisans, commercants, chefs entreprise'), ('2', 'cadres et professions intellectuelles superieures'), ('3', 'professions intermediaires'), ('4', 'employes'), ('5', 'ouvriers'), ('6', 'retraites'), ('7', 'chomeurs'), ('8', 'etudiants'), ('9', 'autres')], max_length=500, null=True),
        ),
    ]
