# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20170107_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recovery',
            options={'ordering': ('recovery_datetime',)},
        ),
    ]
