# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_remove_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
