# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20170111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
