# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20170108_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='forecast_price',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='forecast_time',
        ),
        migrations.AddField(
            model_name='advert',
            name='constraint_time_begin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time begin'),
        ),
        migrations.AddField(
            model_name='advert',
            name='constraint_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time end'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_size',
            field=models.CharField(blank=True, choices=[('1', 'petite voiture'), ('2', 'moyenne voiture'), ('3', 'grande voiture')], max_length=1, verbose_name='car size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date birth'),
        ),
    ]
