# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20170109_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='constraint_time_begin',
            field=models.TimeField(blank=True, null=True, verbose_name='time begin'),
        ),
    ]
