# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20170109_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(choices=[('0', 'NULL'), ('1', 'CAPITOLE'), ('2', 'SAINT-GEORGES'), ('3', 'JUNCASSE - ARGOULETS'), ('4', 'GRAMONT'), ('5', 'LA TERRASSE'), ('6', "ZONES D'ACTIVITES SUD"), ('7', 'FONTAINE-LESTANG'), ('8', 'PONT-DES-DEMOISELLES'), ('9', "PATTE D'OIE"), ('10', 'LE BUSCA'), ('11', 'CROIX-DE-PIERRE'), ('12', 'REYNERIE'), ('13', 'MATABIAU'), ('14', 'FAOURETTE'), ('15', 'SAINT-ETIENNE'), ('16', 'SAINT-SIMON'), ('17', 'LES IZARDS'), ('18', 'SAINT-MARTIN-DU-TOUCH'), ('19', 'LES CHALETS'), ('20', 'LARDENNE'), ('21', 'ARENES'), ('22', 'AMIDONNIERS'), ('23', 'MIRAIL-UNIVERSITE'), ('24', 'LES PRADETTES'), ('25', 'COMPANS'), ('26', 'GINESTOUS'), ('27', 'SAINT-MICHEL'), ('28', 'FER-A-CHEVAL'), ('29', 'BELLEFONTAINE'), ('30', 'SOUPETARD'), ('31', 'PAPUS'), ('32', 'POUVOURVILLE'), ('33', 'BASSO-CAMBO'), ('34', 'ARNAUD BERNARD'), ('35', 'SAINT-AUBIN - DUPUY'), ('36', 'JULES JULIEN'), ('37', 'CROIX-DAURADE'), ('38', 'CASSELARDIT'), ('39', 'MINIMES'), ('40', 'RAMIER'), ('41', 'LA CEPIERE'), ('42', 'EMPALOT'), ('43', 'LALANDE'), ('44', 'RANGUEIL - CHR - FACULTES'), ('45', 'CARMES'), ('46', 'LA FOURGUETTE'), ('47', 'BARRIERE-DE-PARIS'), ('48', 'MONTAUDRAN - LESPINET'), ('49', 'SAINT-AGNE'), ('50', 'PURPAN'), ('51', 'SAUZELONG - RANGUEIL'), ('52', 'SAINT-CYPRIEN'), ('53', 'BAGATELLE'), ('54', 'GUILHEMERY'), ('55', 'MARENGO - JOLIMONT'), ('56', 'COTE PAVEE'), ('57', "CHATEAU-DE-L'HERS"), ('58', 'ROSERAIE'), ('59', 'BONNEFOY'), ('60', 'SEPT DENIERS')], max_length=2, verbose_name='name district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(choices=[('1', 'armoire'), ('2', 'buffet'), ('3', 'canape'), ('4', 'chaise'), ('5', 'commode'), ('6', 'etagere'), ('7', 'fauteuil'), ('8', 'fenetre'), ('9', 'lit'), ('10', 'matelas'), ('11', 'porte'), ('12', 'pouf'), ('13', 'table'), ('14', 'table de chevet'), ('15', 'tabouret'), ('16', 'bougeoire'), ('17', 'cadre'), ('18', 'coussin'), ('19', 'luminaire'), ('20', 'miroir'), ('21', 'pendule'), ('22', 'rideau'), ('23', 'tapis'), ('24', 'vase'), ('25', 'barbecue'), ('26', 'echelle'), ('27', 'hamac'), ('28', 'parasol'), ('29', 'bois'), ('30', 'carton'), ('31', 'ceramique'), ('32', 'metal'), ('33', 'papier'), ('34', 'plastique'), ('35', 'tissu'), ('36', 'verre'), ('37', 'aspirateur'), ('38', 'climatiseur'), ('39', 'congelateur'), ('40', 'four'), ('41', 'refrigerateur'), ('42', 'lave_vaisselle'), ('43', 'lave-linge'), ('44', 'poele à bois'), ('45', 'ventilateur'), ('46', 'balance'), ('47', 'batteur'), ('48', 'bouilloire'), ('49', 'cafetiere'), ('50', 'crepiere'), ('51', 'fer a repasser'), ('52', 'friteuse'), ('53', 'gauffrier'), ('54', 'grille-pain'), ('55', 'machine a fondue'), ('56', 'pese personne'), ('57', 'plancha'), ('58', 'plaque de cuisson'), ('59', 'raclette'), ('60', 'radiateur'), ('61', 'bonnet'), ('62', 'chaussure'), ('63', 'chemise'), ('64', 'couverture'), ('65', 'gants'), ('66', 'pantalon'), ('67', 'pull'), ('68', 'serviette'), ('69', 'short'), ('70', 't-shirt'), ('71', 'veste'), ('72', 'assiette'), ('73', 'casserole'), ('74', 'faitout'), ('75', 'plateau'), ('76', 'saladier'), ('77', 'theiere'), ('78', 'verre'), ('79', 'couvert'), ('80', 'roller'), ('81', 'skateboard'), ('82', 'trottinette'), ('83', 'velo'), ('84', 'baignoire'), ('85', 'bocal'), ('86', 'boite'), ('87', 'bouteille'), ('88', 'lavabo'), ('89', 'sac'), ('90', 'tonneau'), ('91', 'valise'), ('92', 'mixeur'), ('93', 'micro onde'), ('94', 'poele'), ('95', 'ski'), ('96', 'snowboard')], max_length=2, verbose_name='Sub-category name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
