# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20170109_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_size',
            field=models.CharField(blank=True, choices=[('1', 'petite voiture'), ('2', 'moyenne voiture'), ('3', 'grande voiture')], max_length=1, null=True, verbose_name='car size'),
        ),
    ]
