# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20170109_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OAuth id'),
        ),
    ]
